[server]
hostname = "localhost"

[keystore.tls]
file_name = "wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[[custom_message_formatters]]
content_type = "application/edi-hl7"
class = "org.wso2.carbon.business.messaging.hl7.message.HL7MessageFormatter"

[[custom_message_builders]]
content_type = "application/edi-hl7"
class = "org.wso2.carbon.business.messaging.hl7.message.HL7MessageBuilder"

[[custom_transport.listener]]
protocol = "hl7"
class = "org.wso2.carbon.business.messaging.hl7.transport.HL7TransportListener"

[[custom_transport.sender]]
protocol = "hl7"
class = "org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender"
